<b>Data Mahasiswa dan Kegiatan Ekstrakurikuler</b><br>
<ol> <li>Usia</li>
    <li>Gender</li>
    <li>Jurusan</li>
    <li>Organisasi</li>
    <li>Tingkat-Aktif</li>
    <li>Semester</li>
    <li>Nilai Etika</li>
    <li>Nilai Soft Skill</li>
    <li>Kontribusi</li>
    <li>Penghargaan</li>
</ol>

In [10]:
import numpy as np
import pandas as pd

n_data = 1000

# Data acak
usia = np.random.randint(18, 25, size=n_data)
gender = np.random.choice(['L', 'P'], size=n_data)
jurusan = np.random.choice(['TI', 'TS', 'TE', 'TM'], size=n_data)
organisasi = np.random.choice(['BEM', 'HIMA', 'UKM Musik', 'UKM Olahraga', 'Tidak Aktif'], size=n_data)
tingkat_aktif = np.random.choice(['Sangat Aktif', 'Aktif', 'Kurang Aktif', 'Pasif'], size=n_data)
semester = np.random.randint(1, 9, size=n_data)
nilaiEtika = np.round(np.random.uniform(2.0, 4.0, size=n_data), 2)
nilaiSoftskill = np.round(np.random.uniform(2.0, 4.0, size=n_data), 2)
kontribusi = np.random.choice(['Tinggi', 'Sedang', 'Rendah'], size=n_data)
penghargaan = np.random.choice(['Ya', 'Tidak'], size=n_data)

# Buat DataFrame
df = pd.DataFrame({
    'Usia': usia,
    'Gender': gender,
    'Jurusan': jurusan,
    'Organisasi': organisasi,
    'Tingkat Aktif': tingkat_aktif,
    'Semester': semester,
    'Nilai Etika': nilaiEtika,
    'Nilai Softskill': nilaiSoftskill,
    'Kontribusi': kontribusi,
    'Penghargaan': penghargaan
})

# Analisis dasar
print(df.info())
print(f"Usia termuda: {df.Usia.min()}")
print(f"Usia tertua: {df.Usia.max()}")
print(f"Jumlah mahasiswa laki-laki: {len(df[df['Gender'] == 'L'])}")
print(f"Jumlah mahasiswa perempuan: {len(df[df['Gender'] == 'P'])}")
print(f"Jumlah mahasiswa tiap jurusan:\n{df['Jurusan'].value_counts()}")
print(f"Jumlah mahasiswa tiap organisasi:\n{df['Organisasi'].value_counts()}")
print(f"Jumlah mahasiswa dengan tingkat aktif:\n{df['Tingkat Aktif'].value_counts()}")
print(f"Rata-rata nilai etika: {df['Nilai Etika'].mean():.2f}")
print(f"Rata-rata nilai softskill: {df['Nilai Softskill'].mean():.2f}")
print(f"Jumlah kontribusi:\n{df['Kontribusi'].value_counts()}")
print(f"Jumlah yang mendapat penghargaan: {len(df[df['Penghargaan'] == 'Ya'])}")
print(f"Jumlah semester akhir (>= 7): {len(df[df['Semester'] >= 7])}")

# Simpan ke CSV
df.to_csv('dataMahasiswaEkstrakurikuler.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Usia             1000 non-null   int32
 1   Gender           1000 non-null   object
 2   Jurusan          1000 non-null   object
 3   Organisasi       1000 non-null   object
 4   Tingkat Aktif    1000 non-null   object
 5   Semester         1000 non-null   int32
 6   Nilai Etika      1000 non-null   float64
 7   Nilai Softskill  1000 non-null   float64
 8   Kontribusi       1000 non-null   object
 9   Penghargaan      1000 non-null   object
dtypes: float64(2), int32(2), object(6)
memory usage: 70.4+ KB
None
Usia termuda: 18
Usia tertua: 24
Jumlah mahasiswa laki-laki: 516
Jumlah mahasiswa perempuan: 484
Jumlah mahasiswa tiap jurusan:
Jurusan
TM    259
TE    252
TS    248
TI    241
Name: count, dtype: int64
Jumlah mahasiswa tiap organisasi:
Organisasi
UKM Olahraga    214
BEM             200
HIMA            199
UKM Musik       196
Tidak Aktif     191
Name: count, dtype: int64
Jumlah mahasiswa dengan tingkat aktif:
Tingkat Aktif
Sangat Aktif    265
Pasif           250
Aktif           250
Kurang Aktif    235
Name: count, dtype: int64
Rata-rata nilai etika: 2.98
Rata-rata nilai softskill: 2.96
Jumlah kontribusi:
Kontribusi
Sedang    346
Rendah    340
Tinggi    314
Name: count, dtype: int64
Jumlah yang mendapat penghargaan: 523
Jumlah semester akhir (>= 7): 233